blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Questions & Support"
    url: "https://github.com/IShix-g/Logify-Unity-Docs/discussions/new?category=q-a"
    about: "Usage, configuration, or general questions. Please use Discussions instead of Issues."